pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }

    stages {

        stage('Init') {
            steps {
                sh """
                cd /session-01/ec2
                terraform init -reconfigure
                """
            }
        }

        stage('Plan') {
            steps {
                sh """
                cd /session-01/ec2
                terraform plan
                """
            }
        }

        stage('creation') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }

            steps {
                sh """
                cd /session-01/ec2
                terraform apply --auto-approve
                """
            }
        }
        stage('destruction') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }

            steps {
                sh """
                cd /session-01/ec2
                terraform destroy --auto-approve
                """
            }
        }
    }

    post {

        always {
            echo 'this will run every time'
        }

        failure {
            echo 'this will run when there is failure'
        }

        success {
            echo 'this will run when there is success'
        }
    }
}
